#app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: styles
- url: /jsDir 
  static_dir: jsDir

- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest